import ActionCheckBox from "../_components/inputs/ActionCheckBox";

export const Airlines = [
  {
    value: "AA",
    label: "American Airlines",
  },
  {
    value: "AS",
    label: "Alaska Airlines",
  },
  {
    value: "B6",
    label: "JetBlue Airways",
  },
  {
    value: "DL",
    label: "Delta Air Lines",
  },
  {
    value: "F9",
    label: "Frontier Airlines",
  },
  {
    value: "G4",
    label: "Allegiant Air",
  },
  {
    value: "HA",
    label: "Hawaiian Airlines",
  },
  {
    value: "NK",
    label: "Spirit Airlines",
  },
  {
    value: "SY",
    label: "Sun Country Airlines",
  },
  {
    value: "UA",
    label: "United Airlines",
  },
  {
    value: "WN",
    label: "Southwest Airlines",
  },
];

export const itemTypes = [
  {
    category: "Personal Items",
    items: [
      "Wallet",
      "Mobile Phone",
      "Passport",
      "ID Card",
      "Credit Cards",
      "Glasses/Sunglasses",
      "Keys",
      "Jewelry",
      "Wristwatches",
    ],
  },
  {
    category: "Electronics",
    items: [
      "Laptop",
      "Headphones",
      "Tablet",
      "Camera",
      "Charger/Cable",
      "Power Bank",
    ],
  },
  {
    category: "Luggage & Bags",
    items: ["Handbag", "Backpack", "Suitcase", "Gym Bag", "Briefcase"],
  },
  {
    category: "Clothing & Personal Items",
    items: ["Coat/Jacket", "Hat", "Scarf", "Gloves", "Shoes"],
  },
  {
    category: "Documents",
    items: ["Travel Tickets", "Documents", "Certificates"],
  },
  {
    category: "Children's Items",
    items: ["Stroller", "Toy", "Diaper Bag", "Baby Bottle"],
  },
  {
    category: "Sports & Leisure Items",
    items: ["Sports Equipment", "Books/Magazines", "Musical Instruments"],
  },
  {
    category: "Miscellaneous Items",
    items: [
      "Water Bottle",
      "Umbrella",
      "Cosmetics/Makeup",
      "Medical Supplies",
      "Travel Accessories",
    ],
  },
];

export const locationOptions = [
  {
    category: "Common Locations",
    items: [
      "Security Checkpoint",
      "Departure Lounge",
      "Arrival Hall",
      "Gate",
      "Baggage Claim Area",
      "Check-in Counters",
      "Elevators/Escalators",
      "Parking Area",
      "Restaurants and Cafes",
      "Restrooms",
      "Duty-Free Shops",
      "Customer Service Desk",
    ],
  },
];

export const hotelTableHeaders = [
  { key: "id", label: "ID" },
  { key: "name", label: "Hotel Name" },
  { key: "manager", label: "Manager Name" },
  { key: "branches", label: "Hotel Branches" },
  { key: "phone", label: "Contact Number" },
  { key: "location", label: "Address" },
  { key: "email", label: "Primary Email" },
  //status
  // {
  //   key: "status",
  //   label: "Status"
  // },
];

export const hotelTableData = [
  {
    id: "1", // Unique identifier for each row
    name: "Grand Palace",
    manager: "John Doe",
    branches: 5,
    phone: "+123456789",
    location: "123 Main St, Cityville",
    email: "contact@grandpalace.com",
    status : 'underReview'
  },
  {
    id: "2",
    name: "Sea Breeze",
    manager: "Jane Smith",
    branches: 3,
    phone: "+987654321",
    location: "456 Ocean Dr, Beachtown",
    email: "info@seabreeze.com",
    status : 'resolved'
  },
  {
    id: "3",
    name: "Mountain Retreat",
    manager: "Alice Johnson",
    branches: 2,
    phone: "+1122334455",
    location: "789 Hilltop Rd, Mountainview",
    email: "stay@mountainretreat.com",
  },
  {
    id: "4",
    name: "City Center Inn",
    manager: "Bob Brown",
    branches: 4,
    phone: "+2233445566",
    location: "101 Center Plaza, Metropolis",
    email: "hello@citycenterinn.com",
  },
  {
    id: "5",
    name: "Lakeside Resort",
    manager: "Carol White",
    branches: 6,
    phone: "+3344556677",
    location: "202 Lakeview Blvd, Laketown",
    email: "reservations@lakesideresort.com",
  },
  {
    id: "6",
    name: "Desert Oasis",
    manager: "David Green",
    branches: 1,
    phone: "+4455667788",
    location: "303 Desert Rd, Sandville",
    email: "contact@desertoasis.com",
  },
  {
    id: "7",
    name: "Forest Lodge",
    manager: "Eve Black",
    branches: 2,
    phone: "+5566778899",
    location: "404 Forest Ln, Woodsville",
    email: "info@forestlodge.com",
  },
  {
    id: "8",
    name: "Urban Stay",
    manager: "Frank Blue",
    branches: 3,
    phone: "+6677889900",
    location: "505 Urban St, Citytown",
    email: "contact@urbanstay.com",
  },
  {
    id: "9",
    name: "Beachfront Hotel",
    manager: "Grace Yellow",
    branches: 4,
    phone: "+7788990011",
    location: "606 Beach Rd, Seaside",
    email: "info@beachfronthotel.com",
  },
  {
    id: "10",
    name: "Countryside Inn",
    manager: "Henry Purple",
    branches: 2,
    phone: "+8899001122",
    location: "707 Country Ln, Ruralville",
    email: "stay@countrysideinn.com",
  },
];

export const airportTableHeaders = [
  { key: "id", label: "ID" },
  { key: "name", label: "Airport Name" },
  { key: "manager", label: "Manager Name" },
  { key: "airlines", label: "Number of Airlines" },
  { key: "phone", label: "Contact Number" },
  { key: "location", label: "Address" },
  { key: "email", label: "Primary Email" },
];

export const airportTableData = [
  {
    id: "1",
    name: "Sky Harbor International",
    manager: "Emily Davis",
    airlines: 25,
    phone: "+123456789",
    location: "123 Aviation Ave, Phoenix",
    email: "info@skyharbor.com",
    status: "active",
  },
  {
    id: "2",
    name: "JFK International",
    manager: "Robert Johnson",
    airlines: 50,
    phone: "+987654321",
    location: "456 Queens Blvd, New York",
    email: "contact@jfkairport.com",
    status: "underMaintenance",
  },
  {
    id: "3",
    name: "LAX Airport",
    manager: "Sarah Lee",
    airlines: 45,
    phone: "+1122334455",
    location: "789 Aviation Blvd, Los Angeles",
    email: "support@laxairport.com",
  },
  {
    id: "4",
    name: "Chicago O'Hare",
    manager: "William Brown",
    airlines: 60,
    phone: "+2233445566",
    location: "101 Runway St, Chicago",
    email: "help@ohare.com",
  },
  {
    id: "5",
    name: "Miami International",
    manager: "Linda White",
    airlines: 30,
    phone: "+3344556677",
    location: "202 Tropical Rd, Miami",
    email: "reservations@miamiairport.com",
  },
  {
    id: "6",
    name: "Denver International",
    manager: "Michael Green",
    airlines: 35,
    phone: "+4455667788",
    location: "303 Mountain View Dr, Denver",
    email: "contact@denverairport.com",
  },
  {
    id: "7",
    name: "Seattle-Tacoma",
    manager: "Elizabeth Black",
    airlines: 40,
    phone: "+5566778899",
    location: "404 Pacific Hwy, Seattle",
    email: "info@seatac.com",
  },
  {
    id: "8",
    name: "Atlanta Hartsfield-Jackson",
    manager: "James Blue",
    airlines: 80,
    phone: "+6677889900",
    location: "505 Peachtree St, Atlanta",
    email: "support@atlairport.com",
  },
  {
    id: "9",
    name: "Orlando International",
    manager: "Patricia Yellow",
    airlines: 20,
    phone: "+7788990011",
    location: "606 Magic Blvd, Orlando",
    email: "info@orlandoairport.com",
  },
  {
    id: "10",
    name: "San Francisco International",
    manager: "Charles Purple",
    airlines: 55,
    phone: "+8899001122",
    location: "707 Bayview Ln, San Francisco",
    email: "contact@sfairport.com",
  },
];

export const airlineTableHeaders = [
  { key: "id", label: "ID" },
  { key: "name", label: "Airline Name" },
  { key: "ceo", label: "CEO Name" },
  { key: "fleetSize", label: "Fleet Size" },
  { key: "phone", label: "Contact Number" },
  { key: "headquarters", label: "Headquarters" },
  { key: "email", label: "Primary Email" },
];

export const airlineTableData = [
  {
    id: "1",
    name: "SkyFly Airlines",
    ceo: "John Carter",
    fleetSize: 120,
    phone: "+123456789",
    headquarters: "123 Aviation Lane, Dallas",
    email: "info@skyfly.com",
    status: "operational",
  },
  {
    id: "2",
    name: "Eagle Air",
    ceo: "Sophia Green",
    fleetSize: 85,
    phone: "+987654321",
    headquarters: "456 Wing St, Chicago",
    email: "contact@eagleair.com",
    status: "underReview",
  },
  {
    id: "3",
    name: "Oceanic Airlines",
    ceo: "David Miller",
    fleetSize: 60,
    phone: "+1122334455",
    headquarters: "789 Coastal Rd, Miami",
    email: "support@oceanicairlines.com",
  },
  {
    id: "4",
    name: "JetStream",
    ceo: "Emma Davis",
    fleetSize: 140,
    phone: "+2233445566",
    headquarters: "101 Jetway Ave, Atlanta",
    email: "help@jetstream.com",
  },
  {
    id: "5",
    name: "Cloud Nine Air",
    ceo: "Oliver Brown",
    fleetSize: 50,
    phone: "+3344556677",
    headquarters: "202 Skyview Dr, Denver",
    email: "reservations@cloudnineair.com",
  },
  {
    id: "6",
    name: "Horizon Airways",
    ceo: "Ava White",
    fleetSize: 110,
    phone: "+4455667788",
    headquarters: "303 Horizon Ln, Seattle",
    email: "contact@horizonairways.com",
  },
  {
    id: "7",
    name: "Vista Airlines",
    ceo: "Liam Black",
    fleetSize: 95,
    phone: "+5566778899",
    headquarters: "404 Peak St, San Francisco",
    email: "info@vistaairlines.com",
  },
  {
    id: "8",
    name: "Global Wings",
    ceo: "Isabella Blue",
    fleetSize: 200,
    phone: "+6677889900",
    headquarters: "505 Globe Rd, New York",
    email: "support@globalwings.com",
  },
  {
    id: "9",
    name: "Starlight Air",
    ceo: "Ethan Yellow",
    fleetSize: 75,
    phone: "+7788990011",
    headquarters: "606 Star Blvd, Los Angeles",
    email: "info@starlightair.com",
  },
  {
    id: "10",
    name: "Aurora Airways",
    ceo: "Charlotte Purple",
    fleetSize: 90,
    phone: "+8899001122",
    headquarters: "707 Aurora Ln, Anchorage",
    email: "contact@auroraairways.com",
  },
];
